### ISSUE TITLE
Specify JSON standard

### ISSUE THREAD

**Issue by AlexandreRio** [OleVik/grav-plugin-bibliography#1]
Hi,

I got some trouble using your plugin. With your `JSON` file it works fine but I tried to convert my bibtex file into JSON using several converters: `bibtex2bibjson.py`, `bib2sx`, `pandoc-citeproc` … Everytime I get an error.

What JSON standard do you expect? Or, what tool do you use to export your bibtex to JSON format, neither Mendeley nor JabRef support native JSON export.

Regards,

Alex

**Comment by OleVik** [comment]
As CiteProc-JS is the best maintained implementation of CSL, their [example](https://bitbucket.org/fbennett/citeproc-js/src/2b552c68ca2a891d3869ebdfa5167115cc5e546f/demo/citations.json?at=default&fileviewer=file-view-default) is the best one to follow, and what I use to test this plugin.

The problem with Bibtex, and why I deliberately excluded any parser for it from this plugin, is that it is very unreliably formatted. I experimented with various implementations for loosely parsing the Bibtex into JSON, but accounting for variations made it an inefficient approach as Bibtex just is not structured as well as JSON. Depending on the size of your bibliography, I'd suggest one of the following approaches:
1. Import the Bibtex into a bibliography-tool that supports JSON export, then correct formatting as needed
2. Use a Bibtex-converter and correct the formatting of its output
   
   a. If using a programmatic approach, fixing the output should be easier if the bibliography is large
3. Rewrite the bibliography from scratch in JSON. If it is large this obviously would not be efficient

Regardless of how you go about it, having the bibliography available in JSON is ultimately beneficial, as outputting to Bibtex or other formats is much easier from a well-structured JSON-file.

The expected JSON is formatted as closely to CSL as possible, and has been tested with the CiteProc-JS data. An explanation is available here: [CSL-JSON](https://citeproc-js.readthedocs.io/en/latest/csl-json/markup.html), and the schema's definition is available here: [CSL Schema](https://github.com/citation-style-language/schema/tree/4846e02f0a775a8272819204379a4f8d7f45c16c).

I will look into implementing better error-reporting, so that formatting-errors can be discovered more easily.

**Comment by AlexandreRio** [comment]
Ok thanks for your answer, I actually managed to tweak a converter so it finally works seamlessly with my bibtex files :-)

Here is the script that I use to convert my Mendeley bibliography to a valid csl-json ( @austinjp is the original author) according to your plugin.
https://github.com/AlexandreRio/bibtex-to-csl-json

**Comment by austinjp** [comment]
Hi both.

Glad to see someone hacking on this. A decent CSL-JSON implementation would be hugely useful.

My efforts are -- clearly -- part-time and far from elegant. Hacked together "organically" for my own personal requirements. I would not consider this code production ready by a long shot :)

I've had issues with parsing bibtex, wrangling it into JSON, getting CSL to work reliably....

So far it meets my needs, but it doesn't do things elegantly or completely.

Good luck to us all! :)

**Comment by OleVik** [comment]
I do think hacking together a solution for converting or cleaning up formatting of Bibtex-files is the best way to go, as we're ultimately trying to force loosely-structured data into well-structured data - and in this endeavor there are no elegant solutions to handle all varieties of Bibtex-formatting.

Your [bibtex-to-csl-json](https://github.com/AlexandreRio/bibtex-to-csl-json), based on @austinjp's script, is a good approach to this as it creates the initial JSON you need for other purposes. And as stated previously, maintaining this data is easier than juggling Bibtex-converters. Thank you both for your input.
