### ISSUE TITLE
Conversion to Json

### ISSUE THREAD

**Issue by omz13** [OleVik/grav-plugin-bibliography#2]
Sorry to report, none of the bibliographic mangers I use support JSON format (and I don't think I've ever seen it listed as an option elsewhere). This plugin would be more useful if it could simple work with BibTex (which is very much _de facto_) and somehow internally convert it to JSON format for processing.

**Comment by OleVik** [comment]
I would agree that export/import capabilities of many managers is lacking, but for example [Zotero supports it](https://www.zotero.org/support/dev/data_formats#csl_json). The problem with BibTeX is that files vary wildly in formatting, and accounting for differences requires a lot of overhead in scripting - making the plugin very slow, and decent code-coverage difficult to achieve.

An alternative is using the [BiBLaTeX](https://github.com/OleVik/grav-plugin-biblatex)-plugin, but I would highly suggest you consider a workflow which allows you to export CSL-JSON. I should note that any JSON that works with CSL will be valid with this plugin. In addition to Zotero, Pandoc's Citeproc supports converting BibTeX to JSON through: `pandoc-citeproc --bib2json foo.bib > foo.json` ([ref](https://tex.stackexchange.com/a/268305/66574)).

The problem with internal conversions is the dependency-stack: Ideally I would just include Pandoc, arguably the most versatile tool for this job, with the plugin - but within the constraints of a PHP-plugin for a PHP-CMS I cannot predict whether it will successfully run on the variety of systems people run Grav on. The plugin would need to download and install Haskell and Pandoc on the local system, possibly also compile them, which is well outside the scope and security of a plugin.

This plugin is in essence a wrapper around [citeproc-php](https://github.com/seboettg/citeproc-php/), which is an implementation of the CSL-standard in PHP. Given a reliable, maintained BibTeX-parser in PHP (like [this](https://github.com/geissler/converter), which sadly seems to be lacking code-coverage) I would gladly implement an internal converter, but as it stands most packages which deal with this only parse BibTeX into HTML - and not reliably.

**Comment by omz13** [comment]
I use [Papers](http://papersapp.com) as my reference manager. Works well (and I've a substantial collection managed by it). But it doesn't do CSL-JSON. I've looked and CSL-JSON generation is rather rare... [BibSonomy](https://www.bibsonomy.org) does it (if you like web-based services)... and that's about it. I agree that BibTeX can vary wildly, but it still pretty much _de facto_.

I've been using Jekyll, and [jekyll-scholar](https://github.com/inukshuk/jekyll-scholar) which does a good job of managing the references... I was hoping to find something similar for Grav as I'm looking to move in that direction.

Thanks for the pointer to [BiBLaTeX](https://github.com/OleVik/grav-plugin-biblatex).

The [converter](https://github.com/geissler/converter) looks interesting - if perhaps a bit unmaintained - so maybe wrangling that into my workflow somehow.

Or perhaps [this php bibtex parser](https://github.com/renanbr/bibtex-parser) which is more maintained.

**Comment by OleVik** [comment]
Could you share one of your (larger) BibTeX files? With some extensive, uniformly formatted case-data I can better test the code-coverage of a parser as middleware.

**Comment by omz13** [comment]
I have created two files for you: [mava-rp.bib](https://mava.omz13.com/bib/mava-rp.bib) and [mava-rp-complete.bib](https://mava.omz13.com/bib/mava-rp-complete.bib). They are a bibliography of 104 papers (from my MA paper)... the first file has limited fields.... the second one has a more complete set of fields (and more likely to cause problems). Let me know if you need more.

**Comment by OleVik** [comment]
In basic tests the Renanbr/bibtex-parser will work _somewhat_ with the "basic" BibTeX-file, but fail utterly with the "extended" one. Geissler/converter fails utterly with both, mainly because the library upon which it is written is not up to scratch. With both libraries, and others I've reviewed, the larger problem is maintenance: They are either written with a too specific scope, not taking into account enough cases to provide satisfactory code-coverage, or they do not follow standards well enough - which is indeed the broader problem with BibTeX-files generally.

Whilst BibTeX is the common standard within academia, or at least in use with LaTeX and PDF-compilers, it really does not fit well into the web-ecosystem because no authoritative packages are maintained that follow the relatively strict standards of code on the web. Iterative processing is fine as long as exceptions are meaningfully thrown and sensible fallbacks maintained, but as BibTeX itself varies so much the library would be enormous. This is also the case with virtually all parsers I've come across: They fail with the variety of cases presented, and PHP is a processor, not a compiler. When the parser can fail with any poorly formatted entry, it will effectively render the websites (and thus, display) useless until all errors are resolved.

You'd end up recursively adding case-specific considerations, refactoring, or rewriting the source BibTeX-file, both of which would take longer than rewriting the whole of the bibliography into a more permissive format, like JSON.

**Comment by OleVik** [comment]
Marking this as unsolvable because no PHP-parser is currently equipped to deal with the varieties of formatting BibTeX allows.
